import Link from "next/link";
import { PublicationStatus } from "@prisma/client";
import { addScenarioActionAction, addScenarioStepAction, createDepartmentAction, updateDepartmentContentAction, updateDepartmentHeadAction, updateScenarioAction } from "@/features/admin/server/actions";
import { logoutAction } from "@/features/auth/server/actions";
import { requireAdmin } from "@/features/auth/server/session";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ department?: string }> }) {
  const admin = await requireAdmin();
  const departments = await db.department.findMany({ orderBy: { sortOrder: "asc" }, include: { head: true, reference: true, scenario: { include: { steps: { include: { actions: true } } } }, media: true } });
  const { department: selectedId } = await searchParams;
  const selected = departments.find((item) => item.id === selectedId) ?? departments[0];

  return <main className="admin-body"><div className="admin-shell">
    <aside className="admin-nav"><a className="brand" href="/admin"><span className="brand-mark">+</span><span>ИРИС</span></a><a href="#departments" aria-current="page">Отделения</a><a href="#content">Тексты и справка</a><a href="#scenario">Сценарий</a><a href="#media">Видео и памятки</a><a href="#head">Заведующий</a><form action={logoutAction}><button type="submit">Выйти</button></form></aside>
    <section className="admin-main"><header className="admin-top"><div><p className="eyebrow">Администратор: {admin.displayName}</p><h1>Контент портала</h1><p>Портал показывает пациентам только опубликованные данные.</p></div><span className="badge">До 20 отделений</span></header>
    <div className="admin-grid"><div>
      <section id="departments" className="admin-card"><h2>Отделения</h2><div className="admin-list">{departments.map((item) => <Link key={item.id} href={`/admin?department=${item.id}`}>{item.name} <span className="badge">{item.status === PublicationStatus.PUBLISHED ? "Опубликовано" : "Черновик"}</span></Link>)}</div><form action={createDepartmentAction}><label>Новое отделение<input name="name" placeholder="Например, Кардиология" required /></label><label>URL-код латиницей<input name="slug" placeholder="cardiology" required pattern="[a-z0-9-]+" /></label><button type="submit">Добавить отделение</button></form></section>
      {selected ? <>
      <section id="content" className="admin-card"><h2>{selected.name}: тексты и справка</h2><form action={updateDepartmentContentAction}><input type="hidden" name="departmentId" value={selected.id} /><label>Короткое описание для первого экрана<textarea name="intro" defaultValue={selected.intro} /></label><label>Заголовок справки<textarea name="referenceTitle" defaultValue={selected.reference?.title ?? "Об отделении"} /></label><label>Текст справки<textarea name="referenceDescription" defaultValue={selected.reference?.description ?? ""} /></label><button type="submit">Сохранить тексты</button></form></section>
      <section id="scenario" className="admin-card"><h2>Сценарий</h2>{selected.scenario ? <><form action={updateScenarioAction}><input type="hidden" name="scenarioId" value={selected.scenario.id} /><label>Заголовок сценария<input name="title" defaultValue={selected.scenario.title} /></label><label>Подсказка<input name="description" defaultValue={selected.scenario.description} /></label><label>Заголовок срочного экрана<input name="emergencyTitle" defaultValue={selected.scenario.emergencyTitle} /></label><label>Текст срочного экрана<textarea name="emergencyBody" defaultValue={selected.scenario.emergencyBody} /></label><button type="submit">Сохранить сценарий</button></form><h3>Шаги и действия</h3><div className="admin-list">{selected.scenario.steps.map((step) => <div key={step.id}><strong>{step.title}</strong><p>{step.description}</p>{step.actions.map((action) => <p key={action.id}>• {action.title} - {action.kind}</p>)}<form action={addScenarioActionAction}><input type="hidden" name="stepId" value={step.id} /><label>Новое действие<input name="title" placeholder="Например, Показать упражнение" required /></label><label>Короткое пояснение<input name="body" /></label><label>Текст кнопки<input name="actionLabel" defaultValue="Открыть" /></label><label>Что делает<select name="kind" defaultValue="INFORMATION"><option value="STEP">Переход к шагу</option><option value="MEDIA">Открывает материал</option><option value="INFORMATION">Показывает справку</option><option value="EMERGENCY">Срочная помощь</option></select></label><button type="submit" className="secondary">Добавить действие</button></form></div>)}</div><form action={addScenarioStepAction}><input type="hidden" name="scenarioId" value={selected.scenario.id} /><label>Новый шаг<input name="title" placeholder="Например, Что вас беспокоит?" required /></label><label>Пояснение шага<input name="description" /></label><button type="submit">Добавить шаг</button></form></> : <p>Сценарий пока не создан.</p>}</section>
      <section id="media" className="admin-card"><h2>Видео и памятки</h2><p>Материалов: {selected.media.length}. Файлы отправляются напрямую в закрытый бакет Timeweb S3 по одноразовой ссылке. Подключу форму загрузки следующим небольшим шагом, когда вы дадите точное имя созданного бакета.</p><div className="admin-list">{selected.media.map((item) => <div key={item.id}><strong>{item.title}</strong><p>{item.kind} · {item.status === PublicationStatus.PUBLISHED ? "опубликовано" : "черновик"}</p></div>)}</div></section>
      <section id="head" className="admin-card"><h2>Заведующий отделением</h2><form action={updateDepartmentHeadAction}><input type="hidden" name="departmentId" value={selected.id} /><label>Имя<input name="firstName" defaultValue={selected.head?.firstName ?? ""} /></label><label>Фамилия<input name="lastName" defaultValue={selected.head?.lastName ?? ""} /></label><label>Отчество<input name="middleName" defaultValue={selected.head?.middleName ?? ""} /></label><label>Должность<input name="roleTitle" defaultValue={selected.head?.roleTitle ?? ""} /></label><label>Описание<textarea name="biography" defaultValue={selected.head?.biography ?? ""} /></label><button type="submit">Сохранить профиль</button></form></section>
      </> : <section className="admin-card"><h2>Нет отделений</h2><p>Добавьте первое отделение, чтобы заполнить материалы для пациентов.</p></section>}
    </div><aside><section className="admin-card"><h2>Перед публикацией</h2><p>Проверьте текст, руководителя, материалы и путь сценария. Черновики пациентам не видны.</p></section></aside></div></section>
  </div></main>;
}
